feature: add sustainable web design model
thegreenwebfoundation/co2.js pull request #58
Opened 2021-12-16 14:41 UTC by drydenwilliams

2022-02-08 09:03 UTC, mrchrisadams commented
Thanks for this @drydenwilliams.

I've added a few comments and requests for changes - mainly code comments and a typo TBH. If you make those changes I'm happy to merge these in, as it's a definite improvement on what we have right now 👍

2022-02-08 09:33 UTC, mrchrisadams commented
Here's the issue for other bits that came up that I think are worth capturing, but not trying to address in this PR. this woudl make sense to use in a future version

https://github.com/thegreenwebfoundation/co2.js/issues/60

2022-02-08 13:31 UTC, mrchrisadams requested changes
Hi Dryden, thanks for making this - there's a few small changes to make.

2022-02-08 13:31 UTC, mrchrisadams commented on src/sustainable-web-design.js
> +  annualSegmentEngergy(annualEnergy) {
small typo here ~~`annualSegmentEngergy`~~ - `annualSegmentEnergy`

2022-02-08 13:31 UTC, mrchrisadams commented on src/sustainable-web-design.js
> +      transferedBytesToGb * KWH_PER_GB * RETURNING_VISITOR_PERCENTAGE +
Given this is representing two separate things, why not make this more explicit with named variables for two separate things?

I can't speak for others, but I think it makes it easier to see errors being introduced when during implementation.

I think this is intended to be roughly equivalent to _Energy per visit in kWh (E)_ part of the model from [the SWD page](https://sustainablewebdesign.org/calculating-digital-emissions/). I've broken it onto separate lines to make it a tad easier to read:

> (Data Transfer per Visit (new visitors) in GB x 0.81kWh/GB x 0.75) 
> + 
> (Data Transfer per Visit (returning visitors) in GB x 0.81kWh/GB x 0.25 x 0.02)
> 
> 

The code in this PR here has `FIRST_TIME_VIEWING_PERCENTAGE` and `RETURNING_VISITOR_PERCENTAGE` the other way around when compared to the initial model.

I also missed it the first time when reviewing this PR 😅

2022-02-09 10:56 UTC, drydenwilliams commented
Thanks @mrchrisadams will take a look through this hopefully this week, thanks for taking the time again!

2022-03-09 18:36 UTC, mrchrisadams commented
Thanks for this Dryden!

I'll merge it in now, and make a bit of time to update the README file as outlined in #60, and make any further tweaks needed to get it ready for publishing a new release.

2022-03-09 18:36 UTC, merged